In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
plt.rc('font', family='AppleGothic')
plt.rcParams['figure.figsize'] = [20, 12]

import warnings
warnings.filterwarnings(action='ignore')

In [2]:
pd.options.display.max_columns = 100
pd.options.display.max_rows = 1000

In [3]:
import os

path = '../상권배후지추정매출/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')] ## 파일명 끝이 .csv인 경우

## csv 파일들을 DataFrame으로 불러와서 concat
df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i, encoding='cp949')
    df = pd.concat([df, data])
    
df = df.reset_index(drop = True)
df.shape

(1434810, 80)

In [4]:
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2014,1,A,골목상권,1000522,목동로9길,CS200041,사진관,161604397,3021,72,28,11,25,13,9,14,14,15,0,2,28,42,25,3,54,47,1,14,39,27,14,5,100042798,61561599,17968044,28371651,18357966,12049227,23295910,24092752,37468847,0,2378575,39876652,84365646,33658152,1325372,93330804,59084230,1309668,13897392,51577338,50762339,25581730,9286565,2409,612,531,410,590,288,590,296,316,0,113,855,1125,865,63,1450,1435,97,683,679,674,441,311,5
1,2014,1,A,골목상권,1000580,공항대로8길,CS100007,치킨전문점,352909128,14422,69,31,12,13,14,13,16,17,14,9,0,3,6,42,40,61,39,2,30,34,19,12,4,235385535,117523593,39085456,44017378,46228033,48626689,57427979,62377271,55146322,34371027,766289,19427117,26559849,139588329,132196517,207375755,124772037,3916726,79855638,104960361,72843384,56004540,14567146,9672,4750,1663,1797,2001,1903,2308,2564,2186,1374,19,557,933,5793,5746,8280,5597,256,3970,4688,2750,1707,510,19
2,2014,1,A,골목상권,1000507,가로공원로58길,CS200028,미용실,174625276,5695,65,35,16,8,13,13,16,18,17,0,3,13,33,45,6,39,61,3,17,23,30,18,10,100494277,74130999,24880663,9925117,19874907,22234389,23579201,38112802,36018197,0,3662572,23549792,58045902,75629543,13737467,54293158,119963965,3764935,36811365,48158550,46409738,28114805,10997731,3458,2237,805,380,684,818,771,1081,1156,0,124,998,1810,2474,289,2639,3044,130,1234,1561,1440,925,391,36
3,2014,1,A,골목상권,1000556,강서로18길,CS300035,인테리어,158530192,1571,88,13,9,8,25,17,29,4,8,0,13,20,35,31,1,31,69,1,7,38,22,23,10,148628711,9901481,6916790,5909822,13908884,19222623,102670592,4233065,5668416,0,74999409,24867373,29254245,27970906,1438259,22555025,135866734,266530,2363344,109859869,16027485,25152714,4751817,1380,191,211,226,259,181,503,118,73,0,225,440,421,455,30,395,1158,20,127,662,366,286,92,21
4,2014,1,A,골목상권,1000509,곰달래로2길,CS100007,치킨전문점,238151311,9718,70,30,13,16,13,14,14,17,14,13,0,1,6,37,43,65,35,2,19,37,21,15,6,156679132,81472179,26684624,32143350,31462781,30124919,36263458,40677054,40795125,65854340,439980,1250909,7281370,66214094,97110618,140559235,78858749,3596772,48538647,82050481,53478587,24612342,7141155,6291,3427,1142,1218,1281,1253,1397,1714,1713,1976,13,72,353,3147,4157,5763,3573,171,2165,3484,2160,1038,316,11

In [5]:
df.isnull().sum()

기준_년_코드            0
기준_분기_코드           0
상권_구분_코드           0
상권_구분_코드_명         0
상권_코드              0
상권_코드_명            0
서비스_업종_코드          0
서비스_업종_코드_명        0
당월_매출_금액           0
당월_매출_건수           0
주중_매출_비율           0
주말_매출_비율           0
월요일_매출_비율          0
화요일_매출_비율          0
수요일_매출_비율          0
목요일_매출_비율          0
금요일_매출_비율          0
토요일_매출_비율          0
일요일_매출_비율          0
시간대_00~06_매출_비율    0
시간대_06~11_매출_비율    0
시간대_11~14_매출_비율    0
시간대_14~17_매출_비율    0
시간대_17~21_매출_비율    0
시간대_21~24_매출_비율    0
남성_매출_비율           0
여성_매출_비율           0
연령대_10_매출_비율       0
연령대_20_매출_비율       0
연령대_30_매출_비율       0
연령대_40_매출_비율       0
연령대_50_매출_비율       0
연령대_60_이상_매출_비율    0
주중_매출_금액           0
주말_매출_금액           0
월요일_매출_금액          0
화요일_매출_금액          0
수요일_매출_금액          0
목요일_매출_금액          0
금요일_매출_금액          0
토요일_매출_금액          0
일요일_매출_금액          0
시간대_00~06_매출_금액    0
시간대_06~11_매출_금액    0
시간대_11~14_매출_금액    0
시간대_14~17_매출_금액    0
시간대_17~21_매출_금액    0
시간대_21~24_매출_금액    0
남성_매출_금액           0
여성_매출_금액           0
연령대_10_매출_금액       0
연령대_20_매출_금액       0
연령대_30_매출_금액       0
연령대_40_매출_금액       0
연령대_50_매출_금액       0
연령대_60_이상_매출_금액    0
주중_매출_건수           0
주말_매출_건수           0
월요일_매출_건수          0
화요일_매출_건수          0
수요일_매출_건수          0
목요일_매출_건수          0
금요일_매출_건수          0
토요일_매출_건수          0
일요일_매출_건수          0
시간대_건수~06_매출_건수    0
시간대_건수~11_매출_건수    0
시간대_건수~14_매출_건수    0
시간대_건수~17_매출_건수    0
시간대_건수~21_매출_건수    0
시간대_건수~24_매출_건수    0
남성_매출_건수           0
여성_매출_건수           0
연령대_10_매출_건수       0
연령대_20_매출_건수       0
연령대_30_매출_건수       0
연령대_40_매출_건수       0
연령대_50_매출_건수       0
연령대_60_이상_매출_건수    0
점포수                0
dtype: int64

## 데이터 전처리

In [6]:
# 점포수 0인 데이터 보정
df['점포수'].loc[df['점포수'] == 0] = 1
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2014,1,A,골목상권,1000522,목동로9길,CS200041,사진관,161604397,3021,72,28,11,25,13,9,14,14,15,0,2,28,42,25,3,54,47,1,14,39,27,14,5,100042798,61561599,17968044,28371651,18357966,12049227,23295910,24092752,37468847,0,2378575,39876652,84365646,33658152,1325372,93330804,59084230,1309668,13897392,51577338,50762339,25581730,9286565,2409,612,531,410,590,288,590,296,316,0,113,855,1125,865,63,1450,1435,97,683,679,674,441,311,5
1,2014,1,A,골목상권,1000580,공항대로8길,CS100007,치킨전문점,352909128,14422,69,31,12,13,14,13,16,17,14,9,0,3,6,42,40,61,39,2,30,34,19,12,4,235385535,117523593,39085456,44017378,46228033,48626689,57427979,62377271,55146322,34371027,766289,19427117,26559849,139588329,132196517,207375755,124772037,3916726,79855638,104960361,72843384,56004540,14567146,9672,4750,1663,1797,2001,1903,2308,2564,2186,1374,19,557,933,5793,5746,8280,5597,256,3970,4688,2750,1707,510,19
2,2014,1,A,골목상권,1000507,가로공원로58길,CS200028,미용실,174625276,5695,65,35,16,8,13,13,16,18,17,0,3,13,33,45,6,39,61,3,17,23,30,18,10,100494277,74130999,24880663,9925117,19874907,22234389,23579201,38112802,36018197,0,3662572,23549792,58045902,75629543,13737467,54293158,119963965,3764935,36811365,48158550,46409738,28114805,10997731,3458,2237,805,380,684,818,771,1081,1156,0,124,998,1810,2474,289,2639,3044,130,1234,1561,1440,925,391,36
3,2014,1,A,골목상권,1000556,강서로18길,CS300035,인테리어,158530192,1571,88,13,9,8,25,17,29,4,8,0,13,20,35,31,1,31,69,1,7,38,22,23,10,148628711,9901481,6916790,5909822,13908884,19222623,102670592,4233065,5668416,0,74999409,24867373,29254245,27970906,1438259,22555025,135866734,266530,2363344,109859869,16027485,25152714,4751817,1380,191,211,226,259,181,503,118,73,0,225,440,421,455,30,395,1158,20,127,662,366,286,92,21
4,2014,1,A,골목상권,1000509,곰달래로2길,CS100007,치킨전문점,238151311,9718,70,30,13,16,13,14,14,17,14,13,0,1,6,37,43,65,35,2,19,37,21,15,6,156679132,81472179,26684624,32143350,31462781,30124919,36263458,40677054,40795125,65854340,439980,1250909,7281370,66214094,97110618,140559235,78858749,3596772,48538647,82050481,53478587,24612342,7141155,6291,3427,1142,1218,1281,1253,1397,1714,1713,1976,13,72,353,3147,4157,5763,3573,171,2165,3484,2160,1038,316,11

In [7]:
# 점포당 평균 데이터 생성
df['점포당_평균_당월_매출'] = df['당월_매출_금액'] / df['점포수']
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수,점포당_평균_당월_매출
0,2014,1,A,골목상권,1000522,목동로9길,CS200041,사진관,161604397,3021,72,28,11,25,13,9,14,14,15,0,2,28,42,25,3,54,47,1,14,39,27,14,5,100042798,61561599,17968044,28371651,18357966,12049227,23295910,24092752,37468847,0,2378575,39876652,84365646,33658152,1325372,93330804,59084230,1309668,13897392,51577338,50762339,25581730,9286565,2409,612,531,410,590,288,590,296,316,0,113,855,1125,865,63,1450,1435,97,683,679,674,441,311,5,3.232088e+07
1,2014,1,A,골목상권,1000580,공항대로8길,CS100007,치킨전문점,352909128,14422,69,31,12,13,14,13,16,17,14,9,0,3,6,42,40,61,39,2,30,34,19,12,4,235385535,117523593,39085456,44017378,46228033,48626689,57427979,62377271,55146322,34371027,766289,19427117,26559849,139588329,132196517,207375755,124772037,3916726,79855638,104960361,72843384,56004540,14567146,9672,4750,1663,1797,2001,1903,2308,2564,2186,1374,19,557,933,5793,5746,8280,5597,256,3970,4688,2750,1707,510,19,1.857416e+07
2,2014,1,A,골목상권,1000507,가로공원로58길,CS200028,미용실,174625276,5695,65,35,16,8,13,13,16,18,17,0,3,13,33,45,6,39,61,3,17,23,30,18,10,100494277,74130999,24880663,9925117,19874907,22234389,23579201,38112802,36018197,0,3662572,23549792,58045902,75629543,13737467,54293158,119963965,3764935,36811365,48158550,46409738,28114805,10997731,3458,2237,805,380,684,818,771,1081,1156,0,124,998,1810,2474,289,2639,3044,130,1234,1561,1440,925,391,36,4.850702e+06
3,2014,1,A,골목상권,1000556,강서로18길,CS300035,인테리어,158530192,1571,88,13,9,8,25,17,29,4,8,0,13,20,35,31,1,31,69,1,7,38,22,23,10,148628711,9901481,6916790,5909822,13908884,19222623,102670592,4233065,5668416,0,74999409,24867373,29254245,27970906,1438259,22555025,135866734,266530,2363344,109859869,16027485,25152714,4751817,1380,191,211,226,259,181,503,118,73,0,225,440,421,455,30,395,1158,20,127,662,366,286,92,21,7.549057e+06
4,2014,1,A,골목상권,1000509,곰달래로2길,CS100007,치킨전문점,238151311,9718,70,30,13,16,13,14,14,17,14,13,0,1,6,37,43,65,35,2,19,37,21,15,6,156679132,81472179,26684624,32143350,31462781,30124919,36263458,40677054,40795125,65854340,439980,1250909,7281370,66214094,97110618,140559235,78858749,3596772,48538647,82050481,53478587,24612342,7141155,6291,3427,1142,1218,1281,1253,1397,1714,1713,1976,13,72,353,3147,4157,5763,3573,171,2165,3484,2160,1038,316,11,2.165012e+07

In [8]:
df['년도_분기'] = df['기준_년_코드'].astype(str) + '_' + df['기준_분기_코드'].astype(str)
df['년도_분기']

0          2014_1
1          2014_1
2          2014_1
3          2014_1
4          2014_1
            ...
1434805    2020_1
1434806    2020_1
1434807    2020_1
1434808    2020_1
1434809    2020_1
Name: 년도_분기, Length: 1434810, dtype: object

In [9]:
df['상권_코드_명'].value_counts()

조원로10길       1758
수유로12길       1752
덕릉로41길       1720
행운1길         1707
동일로173가길     1704
             ...
북촌로5나길        648
동남로82길        553
도봉산4길         477
녹사평대로11길      390
목동중앙로13나길     385
Name: 상권_코드_명, Length: 1010, dtype: int64

In [10]:
df.loc[df['상권_코드_명'] == '조원로10길']

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수,점포당_평균_당월_매출,년도_분기
205,2014,1,A,골목상권,1000829,조원로10길,CS300021,문구,601814513,25067,88,12,20,18,18,19,14,9,3,0,12,23,34,32,0,58,42,1,22,40,24,7,6,576647861,25166652,134888881,106693486,130571761,107608597,96885136,22894988,2271664,1323945,115513777,181078369,228351585,73925842,1620995,86819360,82741103,314648,42976607,65213864,39654818,15095497,6305030,24469,598,5259,4830,4580,4827,4973,503,95,2,4316,8059,8177,4487,26,7367,6608,66,4689,5449,2536,934,301,18,3.343414e+07,2014_1
209,2014,1,A,골목상권,1000829,조원로10길,CS300020,서적,827083369,22072,86,14,21,17,14,12,22,14,0,0,8,18,34,39,1,57,43,1,16,17,19,30,17,672751448,154331921,138695088,127923401,93441174,115062556,197629229,154145794,186127,0,57886924,192391793,313265820,262889235,649597,436324865,347981612,2855850,80882774,171127614,270365112,144050778,115024354,16736,5336,3422,3129,2315,3472,4398,5330,6,0,1158,4577,7668,8651,18,11160,10702,147,3766,6276,5549,3845,2280,8,1.033854e+08,2014_1
219,2014,1,A,골목상권,1000829,조원로10길,CS200008,한의원,363654536,25851,93,7,20,16,18,18,21,7,0,0,7,25,27,40,1,48,52,0,12,23,26,14,26,339303658,24350878,88987380,48985395,77823992,57404227,66102664,24350878,0,0,23952841,105159979,124600977,107558749,2381990,156857377,190033055,373172,39768321,95714674,74298855,66798906,69936506,23956,1895,6281,4033,4535,4157,4950,1895,0,0,3402,6972,7756,7643,78,12724,12564,18,2639,5347,5231,4215,7843,9,4.040606e+07,2014_1
221,2014,1,A,골목상권,1000829,조원로10길,CS200007,치과의원,2692023719,15153,85,15,20,17,16,15,17,15,0,0,11,32,33,24,1,51,49,0,19,24,23,21,13,2379581937,312441782,484589943,493201164,509012339,425495302,467283189,312441782,0,0,260352620,904457161,811085682,691049558,25078698,1338057324,1249236461,3437696,315788953,539598658,570718844,636924118,520825513,13180,1973,3024,2639,2521,2446,2550,1973,0,0,1617,4628,5017,3821,70,7346,7341,76,3010,3532,3504,2863,1705,18,1.495569e+08,2014_1
227,2014,1,A,골목상권,1000829,조원로10길,CS100004,양식음식점,1081861998,29411,75,25,15,13,17,13,17,15,10,4,0,21,13,38,25,47,53,1,31,31,16,13,8,762880779,318981219,138039231,136099305,162643233,150014749,176084261,168081437,150899782,3070789,1683556,303819396,184243140,407692351,181352766,399439864,476171229,8176855,247240639,370912630,182046800,51165904,16068269,22257,7154,4079,4112,4797,4302,4967,3692,3462,163,331,9434,4656,10618,4209,11004,14292,309,9023,10334,3969,1326,340,13,8.322015e+07,2014_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395774,2020,1,A,골목상권,1000829,조원로10길,CS100005,제과점,506072711,63565,79,21,15,15,16,16,17,13,9,0,14,17,19,40,10,43,57,0,29,33,19,12,6,379148703,126924008,68298292,67216265,76265576,75041540,92327030,70587930,56336078,1042245,58171798,81143903,95681752,211038911,58994102,193135602,301886395,2058252,134274384,154851393,94386376,72537436,36914156,48160,15405,9170,8976,10021,9603,10390,8396,7009,167,8550,10071,12210,25444,7123,23931,39037,266,18910,19757,11141,8425,4469,19,2.663541e+07,2020_1
1395775,2020,1,A,골목상권,1000829,조원로10길,CS100004,양식음식점,858345990,27379,83,18,13,16,17,20,17,11,7,8,4,41,10,25,13,56,44,0,29,34,20,11,7,680767097,177578893,100337457,110029286,153633286,163326685,153440383,112503848,65075045,136778569,2116602,218647552,54767015,229582858,216453394,409803138,284593446,1423750,213783132,257690605,148672719,42968009,29858370,22884,4495,3952,4314,4516,5105,4997,2714,1781,328,714,14038,2369,7178,2752,12979,12919,99,9701,9413,3965,1942,783,20,4.291730e+07,2020_1
1395776,2020,1,A,골목상권,1000829,조원로10길,CS100003,일식음식점,1721567998,37934,84,16,15,16,16,18,19,11,5,4,0,36,7,27,26,63,37,0,32,33,15,11,8,1346063577,375504421,213095227,231299151,275121953,277002709,349544537,238188996,137315425,135295000,323470,289273047,95682650,561614562,639379269,966501328,453471955,3656969,361066145,476475637,270114331,198675686,109984514,31250,6684,5280,5814,6279,6757,7120,4197,2487,2248,23,13742,2553,10250,9118,21275,13143,150,11237,11271,5028,3762,2965,29,5.936441e+07,2020_1
1395777,2020,1,A,골목상권,1000829,조원로10길,CS100002,중식음식점,1784915927,84286,75,25,15,15,15,14,16,12,14,4,1,30,13,39,14,64,36,1,26,29,22,16,6,1364816705,420099222,268777897,252963567,266973310,281380969,294720962,218544561,201554661,92347596,10993946,502622902,177224203,695382072,306345208,1044020408,590445993,11209617,470772748,511000932,321457924,229171536,90853642,66115,18171,12374,13145,13236,13443,13917,9348,8823,3265,822,32507,10709,28665,8318,48529,32113,938,26632,23635,14284,10574,4577,31,5.757793e+07,2020_1
1395778,2020,1,A,골목상권,1000829,조원로10길,CS100001,한식음식점,23955751722,754746,77,23,15,15,15,16,17,13,10,3,3,30,10,37,17,68,32,0,19,25,19,21,16,18282318365,5673433357,3174991655,3475388590,3575032860,3770081047,4286824213,3282577478,2390855879,1730689523,526228310,3523601273,1196823896,10013446291,6964962429,14418213930,6688932043,67522067,5181354643,6582324942,3976552790,3295172371,2004219159,597006,157740,112624,118488,118832,121702,125360,87608,70132,44887,37928,243921,59598,238276,130136,470736,238948,2991,189032,213172,122799,108912,72771,288,8.317969e+07,2020_1

In [13]:
df_sales = df.pivot_table(index=['상권_코드', '서비스_업종_코드'], 
               columns='년도_분기', values='점포당_평균_당월_매출')
df_sales.head()

년도_분기                    2014_1        2014_2        2014_3        2014_4  \
상권_코드   서비스_업종_코드
1000001 CS100001   6.092752e+07  7.119277e+07  6.941415e+07  8.371927e+07
        CS100002   7.830883e+07  7.419328e+07  7.638027e+07  9.373318e+07
        CS100003   7.725436e+07  2.934658e+07  4.053009e+07  3.842372e+07
        CS100004   8.113118e+07  9.185987e+07  9.243012e+07  1.814898e+08
        CS100005   3.476190e+07  3.927323e+07  2.214167e+07  2.165559e+07

년도_분기                    2015_1        2015_2        2015_3        2015_4  \
상권_코드   서비스_업종_코드
1000001 CS100001   6.258971e+07  6.645696e+07  6.576536e+07  7.757226e+07
        CS100002   6.686465e+07  7.288815e+07  7.048284e+07  8.242502e+07
        CS100003   2.944173e+07  3.137040e+07  3.018033e+07  3.600755e+07
        CS100004   9.864977e+07  1.076278e+08  9.826663e+07  1.204825e+08
        CS100005   6.659322e+07  6.389587e+07  4.910766e+07  4.643170e+07

년도_분기                    2016_1        2016_2        2016_3        2016_4  \
상권_코드   서비스_업종_코드
1000001 CS100001   7.015885e+07  7.694477e+07  6.880895e+07  7.875741e+07
        CS100002   7.914830e+07  8.162432e+07  7.281198e+07  8.170112e+07
        CS100003   2.957095e+07  2.134013e+07  2.047689e+07  1.988962e+07
        CS100004   1.249218e+08  1.199577e+08  1.055623e+08  1.214002e+08
        CS100005   6.138270e+07  5.458803e+07  4.027121e+07  5.720196e+07

년도_분기                    2017_1        2017_2        2017_3        2017_4  \
상권_코드   서비스_업종_코드
1000001 CS100001   7.059091e+07  7.903866e+07  7.526531e+07  8.380275e+07
        CS100002   7.565919e+07  6.079148e+07  6.052424e+07  7.421462e+07
        CS100003   1.676974e+07  1.191195e+07  1.107833e+07  9.850048e+06
        CS100004   1.088533e+08  1.247839e+08  1.048472e+08  1.149784e+08
        CS100005   4.004742e+07  3.599730e+07  3.233197e+07  4.706873e+07

년도_분기                    2018_1        2018_2        2018_3        2018_4  \
상권_코드   서비스_업종_코드
1000001 CS100001   7.142265e+07  8.301902e+07  7.379520e+07  8.717491e+07
        CS100002   6.538066e+07  7.679618e+07  5.656538e+07  8.571366e+07
        CS100003   1.566458e+07  1.598102e+07  2.662950e+07  2.784196e+07
        CS100004   9.912141e+07  1.228614e+08  1.113682e+08  1.434638e+08
        CS100005   4.145602e+07  3.998182e+07  3.790789e+07  4.543281e+07

년도_분기                    2019_1        2019_2        2019_3        2019_4  \
상권_코드   서비스_업종_코드
1000001 CS100001   6.061903e+07  6.990543e+07  6.424871e+07  7.248866e+07
        CS100002   6.102188e+07  6.731579e+07  6.169022e+07  6.127224e+07
        CS100003   2.361333e+07  4.750040e+06  5.968620e+07  5.298060e+07
        CS100004   8.218444e+07  7.414365e+07  1.105012e+08  1.324672e+08
        CS100005   3.101623e+07  2.955253e+07  2.472802e+07  1.229530e+08

년도_분기                    2020_1        2020_2
상권_코드   서비스_업종_코드
1000001 CS100001   4.478399e+07  5.286996e+07
        CS100002   4.493084e+07  5.258605e+07
        CS100003   3.127229e+07  2.911605e+07
        CS100004   1.025918e+08  1.170693e+08
        CS100005   8.340683e+07  1.046677e+08

In [16]:
df_sales.reset_index(inplace=True)
df_sales.head()

년도_분기,index,상권_코드,서비스_업종_코드,2014_1,2014_2,2014_3,2014_4,2015_1,2015_2,2015_3,2015_4,2016_1,2016_2,2016_3,2016_4,2017_1,2017_2,2017_3,2017_4,2018_1,2018_2,2018_3,2018_4,2019_1,2019_2,2019_3,2019_4,2020_1,2020_2
0,0,1000001,CS100001,6.092752e+07,7.119277e+07,6.941415e+07,8.371927e+07,6.258971e+07,6.645696e+07,6.576536e+07,7.757226e+07,7.015885e+07,7.694477e+07,6.880895e+07,7.875741e+07,7.059091e+07,7.903866e+07,7.526531e+07,8.380275e+07,7.142265e+07,8.301902e+07,7.379520e+07,8.717491e+07,6.061903e+07,6.990543e+07,6.424871e+07,7.248866e+07,4.478399e+07,5.286996e+07
1,1,1000001,CS100002,7.830883e+07,7.419328e+07,7.638027e+07,9.373318e+07,6.686465e+07,7.288815e+07,7.048284e+07,8.242502e+07,7.914830e+07,8.162432e+07,7.281198e+07,8.170112e+07,7.565919e+07,6.079148e+07,6.052424e+07,7.421462e+07,6.538066e+07,7.679618e+07,5.656538e+07,8.571366e+07,6.102188e+07,6.731579e+07,6.169022e+07,6.127224e+07,4.493084e+07,5.258605e+07
2,2,1000001,CS100003,7.725436e+07,2.934658e+07,4.053009e+07,3.842372e+07,2.944173e+07,3.137040e+07,3.018033e+07,3.600755e+07,2.957095e+07,2.134013e+07,2.047689e+07,1.988962e+07,1.676974e+07,1.191195e+07,1.107833e+07,9.850048e+06,1.566458e+07,1.598102e+07,2.662950e+07,2.784196e+07,2.361333e+07,4.750040e+06,5.968620e+07,5.298060e+07,3.127229e+07,2.911605e+07
3,3,1000001,CS100004,8.113118e+07,9.185987e+07,9.243012e+07,1.814898e+08,9.864977e+07,1.076278e+08,9.826663e+07,1.204825e+08,1.249218e+08,1.199577e+08,1.055623e+08,1.214002e+08,1.088533e+08,1.247839e+08,1.048472e+08,1.149784e+08,9.912141e+07,1.228614e+08,1.113682e+08,1.434638e+08,8.218444e+07,7.414365e+07,1.105012e+08,1.324672e+08,1.025918e+08,1.170693e+08
4,4,1000001,CS100005,3.476190e+07,3.927323e+07,2.214167e+07,2.165559e+07,6.659322e+07,6.389587e+07,4.910766e+07,4.643170e+07,6.138270e+07,5.458803e+07,4.027121e+07,5.720196e+07,4.004742e+07,3.599730e+07,3.233197e+07,4.706873e+07,4.145602e+07,3.998182e+07,3.790789e+07,4.543281e+07,3.101623e+07,2.955253e+07,2.472802e+07,1.229530e+08,8.340683e+07,1.046677e+08

In [17]:
df_sales.isnull().sum()

년도_분기
index            0
상권_코드            0
서비스_업종_코드        0
2014_1        7398
2014_2        7022
2014_3        6856
2014_4        6802
2015_1        6972
2015_2        6627
2015_3        6623
2015_4        6577
2016_1        6796
2016_2        6312
2016_3        5995
2016_4        5820
2017_1        6074
2017_2        5930
2017_3        6312
2017_4        6585
2018_1        6688
2018_2        6567
2018_3        6894
2018_4        6855
2019_1       14413
2019_2       14767
2019_3       14709
2019_4       15347
2020_1       15704
2020_2       15577
dtype: int64

In [18]:
df_sales.dropna(inplace=True)

In [19]:
df_sales.head()

년도_분기,index,상권_코드,서비스_업종_코드,2014_1,2014_2,2014_3,2014_4,2015_1,2015_2,2015_3,2015_4,2016_1,2016_2,2016_3,2016_4,2017_1,2017_2,2017_3,2017_4,2018_1,2018_2,2018_3,2018_4,2019_1,2019_2,2019_3,2019_4,2020_1,2020_2
0,0,1000001,CS100001,6.092752e+07,7.119277e+07,6.941415e+07,8.371927e+07,6.258971e+07,6.645696e+07,6.576536e+07,7.757226e+07,7.015885e+07,7.694477e+07,6.880895e+07,7.875741e+07,7.059091e+07,7.903866e+07,7.526531e+07,8.380275e+07,7.142265e+07,8.301902e+07,7.379520e+07,8.717491e+07,6.061903e+07,6.990543e+07,6.424871e+07,7.248866e+07,4.478399e+07,5.286996e+07
1,1,1000001,CS100002,7.830883e+07,7.419328e+07,7.638027e+07,9.373318e+07,6.686465e+07,7.288815e+07,7.048284e+07,8.242502e+07,7.914830e+07,8.162432e+07,7.281198e+07,8.170112e+07,7.565919e+07,6.079148e+07,6.052424e+07,7.421462e+07,6.538066e+07,7.679618e+07,5.656538e+07,8.571366e+07,6.102188e+07,6.731579e+07,6.169022e+07,6.127224e+07,4.493084e+07,5.258605e+07
2,2,1000001,CS100003,7.725436e+07,2.934658e+07,4.053009e+07,3.842372e+07,2.944173e+07,3.137040e+07,3.018033e+07,3.600755e+07,2.957095e+07,2.134013e+07,2.047689e+07,1.988962e+07,1.676974e+07,1.191195e+07,1.107833e+07,9.850048e+06,1.566458e+07,1.598102e+07,2.662950e+07,2.784196e+07,2.361333e+07,4.750040e+06,5.968620e+07,5.298060e+07,3.127229e+07,2.911605e+07
3,3,1000001,CS100004,8.113118e+07,9.185987e+07,9.243012e+07,1.814898e+08,9.864977e+07,1.076278e+08,9.826663e+07,1.204825e+08,1.249218e+08,1.199577e+08,1.055623e+08,1.214002e+08,1.088533e+08,1.247839e+08,1.048472e+08,1.149784e+08,9.912141e+07,1.228614e+08,1.113682e+08,1.434638e+08,8.218444e+07,7.414365e+07,1.105012e+08,1.324672e+08,1.025918e+08,1.170693e+08
4,4,1000001,CS100005,3.476190e+07,3.927323e+07,2.214167e+07,2.165559e+07,6.659322e+07,6.389587e+07,4.910766e+07,4.643170e+07,6.138270e+07,5.458803e+07,4.027121e+07,5.720196e+07,4.004742e+07,3.599730e+07,3.233197e+07,4.706873e+07,4.145602e+07,3.998182e+07,3.790789e+07,4.543281e+07,3.101623e+07,2.955253e+07,2.472802e+07,1.229530e+08,8.340683e+07,1.046677e+08

In [20]:
df_sales.isnull().sum()

년도_분기
index        0
상권_코드        0
서비스_업종_코드    0
2014_1       0
2014_2       0
2014_3       0
2014_4       0
2015_1       0
2015_2       0
2015_3       0
2015_4       0
2016_1       0
2016_2       0
2016_3       0
2016_4       0
2017_1       0
2017_2       0
2017_3       0
2017_4       0
2018_1       0
2018_2       0
2018_3       0
2018_4       0
2019_1       0
2019_2       0
2019_3       0
2019_4       0
2020_1       0
2020_2       0
dtype: int64

In [21]:
X = df_sales.drop(['서비스_업종_코드', '2020_2'], axis=1)
y = df_sales['2020_2']

In [22]:
X.head()

년도_분기,index,상권_코드,2014_1,2014_2,2014_3,2014_4,2015_1,2015_2,2015_3,2015_4,2016_1,2016_2,2016_3,2016_4,2017_1,2017_2,2017_3,2017_4,2018_1,2018_2,2018_3,2018_4,2019_1,2019_2,2019_3,2019_4,2020_1
0,0,1000001,6.092752e+07,7.119277e+07,6.941415e+07,8.371927e+07,6.258971e+07,6.645696e+07,6.576536e+07,7.757226e+07,7.015885e+07,7.694477e+07,6.880895e+07,7.875741e+07,7.059091e+07,7.903866e+07,7.526531e+07,8.380275e+07,7.142265e+07,8.301902e+07,7.379520e+07,8.717491e+07,6.061903e+07,6.990543e+07,6.424871e+07,7.248866e+07,4.478399e+07
1,1,1000001,7.830883e+07,7.419328e+07,7.638027e+07,9.373318e+07,6.686465e+07,7.288815e+07,7.048284e+07,8.242502e+07,7.914830e+07,8.162432e+07,7.281198e+07,8.170112e+07,7.565919e+07,6.079148e+07,6.052424e+07,7.421462e+07,6.538066e+07,7.679618e+07,5.656538e+07,8.571366e+07,6.102188e+07,6.731579e+07,6.169022e+07,6.127224e+07,4.493084e+07
2,2,1000001,7.725436e+07,2.934658e+07,4.053009e+07,3.842372e+07,2.944173e+07,3.137040e+07,3.018033e+07,3.600755e+07,2.957095e+07,2.134013e+07,2.047689e+07,1.988962e+07,1.676974e+07,1.191195e+07,1.107833e+07,9.850048e+06,1.566458e+07,1.598102e+07,2.662950e+07,2.784196e+07,2.361333e+07,4.750040e+06,5.968620e+07,5.298060e+07,3.127229e+07
3,3,1000001,8.113118e+07,9.185987e+07,9.243012e+07,1.814898e+08,9.864977e+07,1.076278e+08,9.826663e+07,1.204825e+08,1.249218e+08,1.199577e+08,1.055623e+08,1.214002e+08,1.088533e+08,1.247839e+08,1.048472e+08,1.149784e+08,9.912141e+07,1.228614e+08,1.113682e+08,1.434638e+08,8.218444e+07,7.414365e+07,1.105012e+08,1.324672e+08,1.025918e+08
4,4,1000001,3.476190e+07,3.927323e+07,2.214167e+07,2.165559e+07,6.659322e+07,6.389587e+07,4.910766e+07,4.643170e+07,6.138270e+07,5.458803e+07,4.027121e+07,5.720196e+07,4.004742e+07,3.599730e+07,3.233197e+07,4.706873e+07,4.145602e+07,3.998182e+07,3.790789e+07,4.543281e+07,3.101623e+07,2.955253e+07,2.472802e+07,1.229530e+08,8.340683e+07

## Train/Test Split

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3, random_state=10)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(len(X_train) + len(X_test))

(30001, 27)
(12858, 27)
(30001,)
(12858,)
42859

## 모델링 + 하이퍼파라미터

In [24]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet, HuberRegressor

# from sklearn.linear_model import PassiveAggressiveRegressor, RANSACRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.kernel_ridge import KernelRidge

# from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

# from sklear.svm import NuSVR
import xgboost
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [25]:
## Pre-allocate models and corresponding parameter candidates
models = []
params = []

In [26]:
model = ('Ridge', Ridge())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]
}

models.append(model)
params.append(param)

In [27]:
model = ('Lasso', Lasso())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]
}

models.append(model)
params.append(param)

In [28]:
model = ('ElasticNet', ElasticNet())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0],
    'l1_ratio': [0.3, 0.5, 0.7]
}

models.append(model)
params.append(param)

In [29]:
model = ('HuberReg', HuberRegressor())
param = {
    'alpha': [0.0001, 0.001, 0.01]
}

models.append(model)
params.append(param)

In [30]:
model = ('CART', DecisionTreeRegressor())
param = {
    'max_depth': [2, 3, 4, 5],
    'min_samples_split': [0.02, 0.05]
}

models.append(model)
params.append(param)

In [31]:
model = ('StandardizedKNN', Pipeline([('Standardization', StandardScaler()), ('KNN', KNeighborsRegressor())]))
param = {
    'KNN__n_neighbors': [5, 10, 15, 20, 25, 30],
    'KNN__weights': ['uniform', 'distance']
}

models.append(model)
params.append(param)

In [33]:
model = ('XGB', XGBRegressor())
param = {'min_child_weight':[0.5, 1.0], 
         'gamma': [0.04],
         'subsample': [0.5],
         'colsample_bytree': [0.5],
         'max_depth': [3, 4]
        
}
models.append(model)
params.append(param)

In [34]:
from pprint import pprint
pprint(models)
print("=" * 60)
pprint(params)

[('Ridge', Ridge()),
 ('Lasso', Lasso()),
 ('ElasticNet', ElasticNet()),
 ('HuberReg', HuberRegressor()),
 ('CART', DecisionTreeRegressor()),
 ('StandardizedKNN',
  Pipeline(steps=[('Standardization', StandardScaler()),
                ('KNN', KNeighborsRegressor())])),
 ('XGB',
  XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=None, gamma=None,
             gpu_id=None, importance_type='gain', interaction_constraints=None,
             learning_rate=None, max_delta_step=None, max_depth=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             random_state=None, reg_alpha=None, reg_lambda=None,
             scale_pos_weight=None, subsample=None, tree_method=None,
             validate_parameters=None, verbosity=None)),
 ('XGB',
  XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=None, gamma=None,
             gpu_id=None, importance_type='gain', interaction_constraints=None,
             learning_rate=None, max_delta_step=None, max_depth=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             random_state=None, reg_alpha=None, reg_lambda=None,
             scale_pos_weight=None, subsample=None, tree_method=None,
             validate_parameters=None, verbosity=None))]
============================================================
[{'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]},
 {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]},
 {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0], 'l1_ratio': [0.3, 0.5, 0.7]},
 {'alpha': [0.0001, 0.001, 0.01]},
 {'max_depth': [2, 3, 4, 5], 'min_samples_split': [0.02, 0.05]},
 {'KNN__n_neighbors': [5, 10, 15, 20, 25, 30],
  'KNN__weights': ['uniform', 'distance']},
 {'colsample_bytree': [0.5],
  'gamma': [0.04],
  'max_depth': [3, 4],
  'min_child_weight': [0.5, 1.0],
  'subsample': [0.5]},
 {'colsample_bytree': [0.5],
  'gamma': [0.04],
  'max_depth': [3, 4],
  'min_child_weight': [0.5, 1.0],
  'subsample': [0.5]}]

## GridSearch with K-fold CV

In [35]:
from sklearn.model_selection import KFold, GridSearchCV
from sklearn import metrics
from datetime import datetime

In [36]:
def gridsearch_cv_for_regression(model, param, kfold, train_input, train_target, scoring='neg_mean_squared_error', n_jobs=-1, tracking=True):

    name = model[0]
    estimator = model[1]
    if tracking:
        start_time = datetime.now()
        print("[%s] Start parameter search for model '%s'" % (start_time, name))
        gridsearch = GridSearchCV(estimator=estimator, param_grid=param, cv=kfold, scoring=scoring, n_jobs=n_jobs)
        gridsearch.fit(train_input, train_target)
        end_time = datetime.now()
        duration_time = (end_time - start_time).seconds
        print("[%s] Finish parameter search for model '%s' (time: %d seconds)" % (end_time, name, duration_time))
        print()
    else:
        gridsearch = GridSearchCV(estimator=estimator, param_grid=param, cv=kfold, scoring=scoring, n_jobs=n_jobs)
        gridsearch.fit(train_input, train_target)
    
    return gridsearch

In [37]:
kfold = KFold(n_splits=10, 
              shuffle=True, 
              random_state=1234)

In [38]:
# Grid search
kfold = KFold(n_splits=10, shuffle=True, random_state=1234)

results = []

for i in range(len(models)):
#for i in range(6):
    model = models[i]
    param = params[i]
    result = gridsearch_cv_for_regression(model=model, param=param, kfold=kfold, train_input=X_train, train_target=y_train)
    print(result.best_score_)
    print(result.best_params_)
    results.append(result)

[2021-07-20 20:39:39.613274] Start parameter search for model 'Ridge'
[2021-07-20 20:39:45.499180] Finish parameter search for model 'Ridge' (time: 5 seconds)

-1409561856872001.2
{'alpha': 10.0}
[2021-07-20 20:39:45.499677] Start parameter search for model 'Lasso'
[2021-07-20 20:40:12.460719] Finish parameter search for model 'Lasso' (time: 26 seconds)

-1409535039003683.5
{'alpha': 0.1}
[2021-07-20 20:40:12.460719] Start parameter search for model 'ElasticNet'
[2021-07-20 20:41:31.877475] Finish parameter search for model 'ElasticNet' (time: 79 seconds)

-1409535039297384.5
{'alpha': 0.1, 'l1_ratio': 0.7}
[2021-07-20 20:41:31.877475] Start parameter search for model 'HuberReg'
[2021-07-20 20:41:39.159628] Finish parameter search for model 'HuberReg' (time: 7 seconds)

-1486509550616068.8
{'alpha': 0.01}
[2021-07-20 20:41:39.159628] Start parameter search for model 'CART'
[2021-07-20 20:41:43.240161] Finish parameter search for model 'CART' (time: 4 seconds)

-3708735444123350.5
{'max_depth': 5, 'min_samples_split': 0.02}
[2021-07-20 20:41:43.240657] Start parameter search for model 'StandardizedKNN'
[2021-07-20 20:43:14.150781] Finish parameter search for model 'StandardizedKNN' (time: 90 seconds)

-2853066301090245.0
{'KNN__n_neighbors': 5, 'KNN__weights': 'distance'}
[2021-07-20 20:43:14.157725] Start parameter search for model 'XGB'
[2021-07-20 20:43:47.454491] Finish parameter search for model 'XGB' (time: 33 seconds)

-2206852136120789.5
{'colsample_bytree': 0.5, 'gamma': 0.04, 'max_depth': 3, 'min_child_weight': 0.5, 'subsample': 0.5}
[2021-07-20 20:43:47.454985] Start parameter search for model 'XGB'
[2021-07-20 20:44:19.634048] Finish parameter search for model 'XGB' (time: 32 seconds)

-2206852136120789.5
{'colsample_bytree': 0.5, 'gamma': 0.04, 'max_depth': 3, 'min_child_weight': 0.5, 'subsample': 0.5}

In [39]:
results[1].best_params_

{'alpha': 0.1}

## Metrics

In [33]:
def MAPE(y_test, y_pred): 
    y_test, y_pred = np.array(y_test), np.array(y_pred)
    mape = 100 - (np.mean(np.abs((y_test - y_pred) / y_test)) * 100)
    return mape


def RMSPE(y_test, y_pred):
    y_test, y_pred = np.array(y_test), np.array(y_pred)
    rmspe = 100 - (np.sqrt(np.mean(((y_test - y_pred) / y_test)**2))*100)
    return rmspe

In [34]:
for i in range(len(results)):
    y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(y_test, y_test_hat))
    mae = metrics.mean_absolute_error(y_test, y_test_hat)
    r2 = metrics.r2_score(y_test, y_test_hat)
    mape = MAPE(y_test, y_test_hat)
    rmspe = RMSPE(y_test, y_test_hat)
    
    print("## %s | RMSE: %.4f, MAE: %.4f, R-square: %.4f, Relative Absolute Error: %.4f%%" % (models[i][0], rmse, mae, r2, mape))

## Ridge | RMSE: 33008371.1134, MAE: 11744249.4305, R-square: 0.9116, Relative Absolute Error: -426.1454%
## Lasso | RMSE: 33008371.1134, MAE: 11744249.4310, R-square: 0.9116, Relative Absolute Error: -426.1454%
## ElasticNet | RMSE: 33008371.1126, MAE: 11744249.4507, R-square: 0.9116, Relative Absolute Error: -426.1454%
## HuberReg | RMSE: 33822471.9818, MAE: 10405120.3208, R-square: 0.9072, Relative Absolute Error: -202.5003%
## CART | RMSE: 70328650.1975, MAE: 14833176.9439, R-square: 0.5989, Relative Absolute Error: -71.5311%
## StandardizedKNN | RMSE: 48646479.8523, MAE: 13881284.7708, R-square: 0.8081, Relative Absolute Error: -3934.4110%
## XGB | RMSE: 35218802.4149, MAE: 11565881.8884, R-square: 0.8994, Relative Absolute Error: -2271.5746%

In [35]:
for i in range(len(params)):
    print(models[i][0], params[i])

Ridge {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]}
Lasso {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]}
ElasticNet {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0], 'l1_ratio': [0.3, 0.5, 0.7]}
HuberReg {'alpha': [0.0001, 0.001, 0.01]}
CART {'max_depth': [2, 3, 4, 5], 'min_samples_split': [0.02, 0.05]}
StandardizedKNN {'KNN__n_neighbors': [5, 10, 15, 20, 25, 30], 'KNN__weights': ['uniform', 'distance']}
XGB {'min_child_weight': [0.5, 1.0], 'gamma': [0.04], 'subsample': [0.5], 'colsample_bytree': [0.5], 'max_depth': [3, 4]}

In [55]:
outcome = pd.DataFrame(columns = ['Model', 'Best_parameter', 'RMSE', 'RMSPE', 'MAE', 'MAPE', 'R-squared' ])
for i in range(len(models)):
    y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(y_test, y_test_hat))
    mae = metrics.mean_absolute_error(y_test, y_test_hat)
    r2 = metrics.r2_score(y_test, y_test_hat)
    outcome = outcome.append(pd.DataFrame([[models[i][0], results[i].best_params_, rmse , rmspe, mae, mape, r2]],
                                 columns = ['Model', 'Best_parameter', 'RMSE', 'RMSPE', 'MAE', 'MAPE', 'R-squared']),
                    ignore_index=True)
    
outcome

,Model,Best_parameter,RMSE,RMSPE,MAE,MAPE,R-squared
0,Ridge,{'alpha': 10.0},3.300837e+07,-250996.578433,1.174425e+07,-2271.57457,0.911637
1,Lasso,{'alpha': 10.0},3.300837e+07,-250996.578433,1.174425e+07,-2271.57457,0.911637
2,ElasticNet,"{'alpha': 10.0, 'l1_ratio': 0.3}",3.300837e+07,-250996.578433,1.174425e+07,-2271.57457,0.911637
3,HuberReg,{'alpha': 0.01},3.382247e+07,-250996.578433,1.040512e+07,-2271.57457,0.907225
4,CART,"{'max_depth': 5, 'min_samples_split': 0.02}",7.032865e+07,-250996.578433,1.483318e+07,-2271.57457,0.598870
5,StandardizedKNN,"{'KNN__n_neighbors': 5, 'KNN__weights': 'dista...",4.864648e+07,-250996.578433,1.388128e+07,-2271.57457,0.808079
6,XGB,"{'colsample_bytree': 0.5, 'gamma': 0.04, 'max_...",3.521880e+07,-250996.578433,1.156588e+07,-2271.57457,0.899407