In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
plt.rc('font', family='AppleGothic')
plt.rcParams['figure.figsize'] = [20, 12]

import warnings
warnings.filterwarnings(action='ignore')

In [2]:
pd.options.display.max_columns = 100
pd.options.display.max_rows = 1000

In [3]:
import os

path = './data/상권배후지추정매출/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')] ## 파일명 끝이 .csv인 경우

## csv 파일들을 DataFrame으로 불러와서 concat
df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i, encoding='cp949')
    df = pd.concat([df, data])
    
df = df.reset_index(drop = True)
df.shape

(1434810, 80)

In [4]:
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2015,1,A,골목상권,1000428,증산서길,CS100005,제과점,284484215,33916,71,30,15,14,13,14,15,15,15,0,14,17,20,35,15,41,59,1,19,28,31,15,7,198729159,85755056,39546242,39128460,35054847,40043260,44956350,44357482,41397574,481061,41371916,45794955,52335101,102816769,41684413,106969928,169353641,3918538,62801204,76576495,75147636,42050058,15829639,24455,9461,5052,5039,4365,4818,5181,4842,4619,60,5582,5672,6125,11621,4856,11990,21138,633,8898,9185,8148,4488,1777,7
1,2015,1,A,골목상권,1000288,오패산로4길,CS300027,섬유제품,12005909,289,76,24,22,17,13,15,9,18,7,0,0,18,22,59,1,40,61,0,5,17,24,30,24,9736459,2269450,2756621,2128936,1424791,2890177,535934,1709233,560217,0,0,2406100,2224724,7292312,82773,4839538,6868387,0,411381,2202727,2380481,3294941,3418394,221,68,66,48,36,44,27,50,18,0,0,54,56,176,3,118,164,0,17,51,64,84,67,4
2,2015,1,A,골목상권,1000270,동소문로26가길,CS200025,자동차수리,71547516,601,77,23,15,15,17,16,14,23,1,0,7,27,31,35,0,69,31,0,13,15,31,27,15,50879960,20667556,10769544,9873111,11454004,7281810,11501491,20482477,185079,0,9360674,16748247,27890492,17548103,0,44823579,17296999,0,2364857,12243705,15718572,24574785,7218662,455,146,94,98,101,64,98,143,3,0,52,157,217,175,0,381,162,0,35,75,167,169,99,7
3,2015,1,A,골목상권,1000284,아리랑로4길,CS200025,자동차수리,80195548,651,78,22,20,16,16,9,17,22,0,0,9,27,34,29,1,66,34,0,5,14,31,34,17,58480589,21714959,13010544,10895286,12456517,6838306,15279936,21529880,185079,0,9739446,18098990,32729013,19542810,85289,51194195,19312565,0,1339555,12540181,17251407,30591683,8783937,497,154,115,107,106,56,113,151,3,0,60,168,240,181,2,409,181,0,24,79,182,198,109,8
4,2015,1,A,골목상권,1000287,오패산로3길,CS300002,편의점,1339105488,240966,70,30,14,14,13,14,15,16,14,16,19,12,12,21,19,66,34,3,36,31,20,8,2,909912741,429192747,178443826,184703161,164202398,181764536,200798820,225436478,203756269,237253866,219256648,146908114,160552017,286388105,288746738,881901743,420784068,30454123,392898087,429826131,301666448,109787815,38053204,166656,74310,32905,34056,30599,33147,35949,38674,35636,38756,43931,29148,29252,51141,48738,158792,77959,7956,86744,70875,47502,17996,5676,11

In [5]:
df.isnull().sum()

기준_년_코드            0
기준_분기_코드           0
상권_구분_코드           0
상권_구분_코드_명         0
상권_코드              0
상권_코드_명            0
서비스_업종_코드          0
서비스_업종_코드_명        0
당월_매출_금액           0
당월_매출_건수           0
주중_매출_비율           0
주말_매출_비율           0
월요일_매출_비율          0
화요일_매출_비율          0
수요일_매출_비율          0
목요일_매출_비율          0
금요일_매출_비율          0
토요일_매출_비율          0
일요일_매출_비율          0
시간대_00~06_매출_비율    0
시간대_06~11_매출_비율    0
시간대_11~14_매출_비율    0
시간대_14~17_매출_비율    0
시간대_17~21_매출_비율    0
시간대_21~24_매출_비율    0
남성_매출_비율           0
여성_매출_비율           0
연령대_10_매출_비율       0
연령대_20_매출_비율       0
연령대_30_매출_비율       0
연령대_40_매출_비율       0
연령대_50_매출_비율       0
연령대_60_이상_매출_비율    0
주중_매출_금액           0
주말_매출_금액           0
월요일_매출_금액          0
화요일_매출_금액          0
수요일_매출_금액          0
목요일_매출_금액          0
금요일_매출_금액          0
토요일_매출_금액          0
일요일_매출_금액          0
시간대_00~06_매출_금액    0
시간대_06~11_매출_금액    0
시간대_11~14_매출_금액    0
시간대_14~17_매출_금액    0
시간대_17~21_매출_금액    0
시간대_21~24_매출_금액    0
남성_매출_금액           0
여성_매출_금액           0
연령대_10_매출_금액       0
연령대_20_매출_금액       0
연령대_30_매출_금액       0
연령대_40_매출_금액       0
연령대_50_매출_금액       0
연령대_60_이상_매출_금액    0
주중_매출_건수           0
주말_매출_건수           0
월요일_매출_건수          0
화요일_매출_건수          0
수요일_매출_건수          0
목요일_매출_건수          0
금요일_매출_건수          0
토요일_매출_건수          0
일요일_매출_건수          0
시간대_건수~06_매출_건수    0
시간대_건수~11_매출_건수    0
시간대_건수~14_매출_건수    0
시간대_건수~17_매출_건수    0
시간대_건수~21_매출_건수    0
시간대_건수~24_매출_건수    0
남성_매출_건수           0
여성_매출_건수           0
연령대_10_매출_건수       0
연령대_20_매출_건수       0
연령대_30_매출_건수       0
연령대_40_매출_건수       0
연령대_50_매출_건수       0
연령대_60_이상_매출_건수    0
점포수                0
dtype: int64

## 데이터 전처리

In [6]:
# 점포수 0인 데이터 보정
df['점포수'].loc[df['점포수'] == 0] = 1
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2015,1,A,골목상권,1000428,증산서길,CS100005,제과점,284484215,33916,71,30,15,14,13,14,15,15,15,0,14,17,20,35,15,41,59,1,19,28,31,15,7,198729159,85755056,39546242,39128460,35054847,40043260,44956350,44357482,41397574,481061,41371916,45794955,52335101,102816769,41684413,106969928,169353641,3918538,62801204,76576495,75147636,42050058,15829639,24455,9461,5052,5039,4365,4818,5181,4842,4619,60,5582,5672,6125,11621,4856,11990,21138,633,8898,9185,8148,4488,1777,7
1,2015,1,A,골목상권,1000288,오패산로4길,CS300027,섬유제품,12005909,289,76,24,22,17,13,15,9,18,7,0,0,18,22,59,1,40,61,0,5,17,24,30,24,9736459,2269450,2756621,2128936,1424791,2890177,535934,1709233,560217,0,0,2406100,2224724,7292312,82773,4839538,6868387,0,411381,2202727,2380481,3294941,3418394,221,68,66,48,36,44,27,50,18,0,0,54,56,176,3,118,164,0,17,51,64,84,67,4
2,2015,1,A,골목상권,1000270,동소문로26가길,CS200025,자동차수리,71547516,601,77,23,15,15,17,16,14,23,1,0,7,27,31,35,0,69,31,0,13,15,31,27,15,50879960,20667556,10769544,9873111,11454004,7281810,11501491,20482477,185079,0,9360674,16748247,27890492,17548103,0,44823579,17296999,0,2364857,12243705,15718572,24574785,7218662,455,146,94,98,101,64,98,143,3,0,52,157,217,175,0,381,162,0,35,75,167,169,99,7
3,2015,1,A,골목상권,1000284,아리랑로4길,CS200025,자동차수리,80195548,651,78,22,20,16,16,9,17,22,0,0,9,27,34,29,1,66,34,0,5,14,31,34,17,58480589,21714959,13010544,10895286,12456517,6838306,15279936,21529880,185079,0,9739446,18098990,32729013,19542810,85289,51194195,19312565,0,1339555,12540181,17251407,30591683,8783937,497,154,115,107,106,56,113,151,3,0,60,168,240,181,2,409,181,0,24,79,182,198,109,8
4,2015,1,A,골목상권,1000287,오패산로3길,CS300002,편의점,1339105488,240966,70,30,14,14,13,14,15,16,14,16,19,12,12,21,19,66,34,3,36,31,20,8,2,909912741,429192747,178443826,184703161,164202398,181764536,200798820,225436478,203756269,237253866,219256648,146908114,160552017,286388105,288746738,881901743,420784068,30454123,392898087,429826131,301666448,109787815,38053204,166656,74310,32905,34056,30599,33147,35949,38674,35636,38756,43931,29148,29252,51141,48738,158792,77959,7956,86744,70875,47502,17996,5676,11

In [7]:
# 점포당 평균 데이터 생성
df['점포당_평균_당월_매출'] = df['당월_매출_금액'] / df['점포수']
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수,점포당_평균_당월_매출
0,2015,1,A,골목상권,1000428,증산서길,CS100005,제과점,284484215,33916,71,30,15,14,13,14,15,15,15,0,14,17,20,35,15,41,59,1,19,28,31,15,7,198729159,85755056,39546242,39128460,35054847,40043260,44956350,44357482,41397574,481061,41371916,45794955,52335101,102816769,41684413,106969928,169353641,3918538,62801204,76576495,75147636,42050058,15829639,24455,9461,5052,5039,4365,4818,5181,4842,4619,60,5582,5672,6125,11621,4856,11990,21138,633,8898,9185,8148,4488,1777,7,4.064060e+07
1,2015,1,A,골목상권,1000288,오패산로4길,CS300027,섬유제품,12005909,289,76,24,22,17,13,15,9,18,7,0,0,18,22,59,1,40,61,0,5,17,24,30,24,9736459,2269450,2756621,2128936,1424791,2890177,535934,1709233,560217,0,0,2406100,2224724,7292312,82773,4839538,6868387,0,411381,2202727,2380481,3294941,3418394,221,68,66,48,36,44,27,50,18,0,0,54,56,176,3,118,164,0,17,51,64,84,67,4,3.001477e+06
2,2015,1,A,골목상권,1000270,동소문로26가길,CS200025,자동차수리,71547516,601,77,23,15,15,17,16,14,23,1,0,7,27,31,35,0,69,31,0,13,15,31,27,15,50879960,20667556,10769544,9873111,11454004,7281810,11501491,20482477,185079,0,9360674,16748247,27890492,17548103,0,44823579,17296999,0,2364857,12243705,15718572,24574785,7218662,455,146,94,98,101,64,98,143,3,0,52,157,217,175,0,381,162,0,35,75,167,169,99,7,1.022107e+07
3,2015,1,A,골목상권,1000284,아리랑로4길,CS200025,자동차수리,80195548,651,78,22,20,16,16,9,17,22,0,0,9,27,34,29,1,66,34,0,5,14,31,34,17,58480589,21714959,13010544,10895286,12456517,6838306,15279936,21529880,185079,0,9739446,18098990,32729013,19542810,85289,51194195,19312565,0,1339555,12540181,17251407,30591683,8783937,497,154,115,107,106,56,113,151,3,0,60,168,240,181,2,409,181,0,24,79,182,198,109,8,1.002444e+07
4,2015,1,A,골목상권,1000287,오패산로3길,CS300002,편의점,1339105488,240966,70,30,14,14,13,14,15,16,14,16,19,12,12,21,19,66,34,3,36,31,20,8,2,909912741,429192747,178443826,184703161,164202398,181764536,200798820,225436478,203756269,237253866,219256648,146908114,160552017,286388105,288746738,881901743,420784068,30454123,392898087,429826131,301666448,109787815,38053204,166656,74310,32905,34056,30599,33147,35949,38674,35636,38756,43931,29148,29252,51141,48738,158792,77959,7956,86744,70875,47502,17996,5676,11,1.217369e+08

In [8]:
df['년도_분기'] = df['기준_년_코드'].astype(str) + '_' + df['기준_분기_코드'].astype(str)
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수,점포당_평균_당월_매출,년도_분기
0,2015,1,A,골목상권,1000428,증산서길,CS100005,제과점,284484215,33916,71,30,15,14,13,14,15,15,15,0,14,17,20,35,15,41,59,1,19,28,31,15,7,198729159,85755056,39546242,39128460,35054847,40043260,44956350,44357482,41397574,481061,41371916,45794955,52335101,102816769,41684413,106969928,169353641,3918538,62801204,76576495,75147636,42050058,15829639,24455,9461,5052,5039,4365,4818,5181,4842,4619,60,5582,5672,6125,11621,4856,11990,21138,633,8898,9185,8148,4488,1777,7,4.064060e+07,2015_1
1,2015,1,A,골목상권,1000288,오패산로4길,CS300027,섬유제품,12005909,289,76,24,22,17,13,15,9,18,7,0,0,18,22,59,1,40,61,0,5,17,24,30,24,9736459,2269450,2756621,2128936,1424791,2890177,535934,1709233,560217,0,0,2406100,2224724,7292312,82773,4839538,6868387,0,411381,2202727,2380481,3294941,3418394,221,68,66,48,36,44,27,50,18,0,0,54,56,176,3,118,164,0,17,51,64,84,67,4,3.001477e+06,2015_1
2,2015,1,A,골목상권,1000270,동소문로26가길,CS200025,자동차수리,71547516,601,77,23,15,15,17,16,14,23,1,0,7,27,31,35,0,69,31,0,13,15,31,27,15,50879960,20667556,10769544,9873111,11454004,7281810,11501491,20482477,185079,0,9360674,16748247,27890492,17548103,0,44823579,17296999,0,2364857,12243705,15718572,24574785,7218662,455,146,94,98,101,64,98,143,3,0,52,157,217,175,0,381,162,0,35,75,167,169,99,7,1.022107e+07,2015_1
3,2015,1,A,골목상권,1000284,아리랑로4길,CS200025,자동차수리,80195548,651,78,22,20,16,16,9,17,22,0,0,9,27,34,29,1,66,34,0,5,14,31,34,17,58480589,21714959,13010544,10895286,12456517,6838306,15279936,21529880,185079,0,9739446,18098990,32729013,19542810,85289,51194195,19312565,0,1339555,12540181,17251407,30591683,8783937,497,154,115,107,106,56,113,151,3,0,60,168,240,181,2,409,181,0,24,79,182,198,109,8,1.002444e+07,2015_1
4,2015,1,A,골목상권,1000287,오패산로3길,CS300002,편의점,1339105488,240966,70,30,14,14,13,14,15,16,14,16,19,12,12,21,19,66,34,3,36,31,20,8,2,909912741,429192747,178443826,184703161,164202398,181764536,200798820,225436478,203756269,237253866,219256648,146908114,160552017,286388105,288746738,881901743,420784068,30454123,392898087,429826131,301666448,109787815,38053204,166656,74310,32905,34056,30599,33147,35949,38674,35636,38756,43931,29148,29252,51141,48738,158792,77959,7956,86744,70875,47502,17996,5676,11,1.217369e+08,2015_1

In [9]:
df['상권_코드_명'].value_counts()

조원로10길       1758
수유로12길       1752
덕릉로41길       1720
행운1길         1707
동일로173가길     1704
             ...
북촌로5나길        648
동남로82길        553
도봉산4길         477
녹사평대로11길      390
목동중앙로13나길     385
Name: 상권_코드_명, Length: 1010, dtype: int64

In [10]:
df.loc[df['상권_코드_명'] == '조원로10길']

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수,점포당_평균_당월_매출,년도_분기
379,2015,1,A,골목상권,1000829,조원로10길,CS300019,의료기기,44396983,983,67,33,23,8,8,5,22,33,0,0,12,43,38,7,0,68,32,0,3,7,16,19,55,24744958,19652025,7281308,4211363,3467185,1471439,8313663,19652025,0,0,3622587,21585609,16406581,2782206,0,33217425,11179558,0,1674396,3636317,3881556,7966070,27238644,703,280,232,85,102,68,216,280,0,0,81,398,419,85,0,544,439,0,51,67,203,254,408,12,3.699749e+06,2015_1
684,2015,1,A,골목상권,1000829,조원로10길,CS300004,핸드폰,2898434640,9436,82,18,23,19,8,13,19,12,6,0,8,35,22,34,1,45,55,5,21,25,21,21,7,2833742850,64691790,1401672728,144928037,136382535,173155868,977603682,47686536,17005254,0,196462809,1004802264,1198514284,493619565,5035718,2222389714,655634992,1206336,330484013,276798416,98071006,419350801,1752114134,7378,2058,2150,1228,944,1099,1957,1251,807,0,944,2533,2039,3532,388,4255,4214,121,3005,2266,1017,1097,966,32,9.057608e+07,2015_1
686,2015,1,A,골목상권,1000829,조원로10길,CS100009,호프-간이주점,8078492174,216028,75,25,14,16,16,13,16,15,10,27,1,3,4,22,44,71,29,0,17,28,23,22,10,6070516653,2007975521,1034519964,1236838567,1144674856,1209213316,1445269950,1238930804,769044717,2541419751,40757787,103263272,74808278,1168949989,4149293097,4758384545,1947415743,53095394,1947435821,2752866672,1224387696,552316791,175697917,160860,55168,28474,32808,29480,31894,38204,33622,21546,61116,1068,7592,1796,34708,109748,127425,62354,1752,62930,74744,31174,14863,4312,127,6.361017e+07,2015_1
2197,2015,1,A,골목상권,1000829,조원로10길,CS300033,철물점,168816697,5684,81,19,16,21,16,14,15,15,4,1,26,24,22,22,6,84,16,0,14,18,31,29,7,124774845,44041852,27321973,27470440,14099410,29757875,26125147,39819054,4222798,1300816,38899569,32387161,39246867,48488982,8493302,114295606,11898953,34011,12024579,23719469,49108795,38027781,3279935,4350,1334,756,1158,954,763,719,771,563,162,734,952,950,1602,1284,3280,1275,12,1599,1476,862,458,151,15,1.125445e+07,2015_1
4042,2015,1,A,골목상권,1000829,조원로10길,CS300026,완구,748038567,15601,54,46,8,11,11,12,12,22,25,0,4,27,35,33,1,52,48,0,8,56,19,8,8,367833501,380205066,57177782,62923299,70414430,87728145,89589845,178985896,201219170,0,29276955,190952877,246993593,269706029,11109113,391461430,320248712,492887,44998652,375222346,156267803,70922549,63805906,7978,7623,1317,1510,1548,1691,1912,3534,4089,0,656,3993,5296,5406,250,8009,6919,18,967,7936,3356,1211,1445,5,1.496077e+08,2015_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395774,2020,1,A,골목상권,1000829,조원로10길,CS100005,제과점,506072711,63565,79,21,15,15,16,16,17,13,9,0,14,17,19,40,10,43,57,0,29,33,19,12,6,379148703,126924008,68298292,67216265,76265576,75041540,92327030,70587930,56336078,1042245,58171798,81143903,95681752,211038911,58994102,193135602,301886395,2058252,134274384,154851393,94386376,72537436,36914156,48160,15405,9170,8976,10021,9603,10390,8396,7009,167,8550,10071,12210,25444,7123,23931,39037,266,18910,19757,11141,8425,4469,19,2.663541e+07,2020_1
1395775,2020,1,A,골목상권,1000829,조원로10길,CS100004,양식음식점,858345990,27379,83,18,13,16,17,20,17,11,7,8,4,41,10,25,13,56,44,0,29,34,20,11,7,680767097,177578893,100337457,110029286,153633286,163326685,153440383,112503848,65075045,136778569,2116602,218647552,54767015,229582858,216453394,409803138,284593446,1423750,213783132,257690605,148672719,42968009,29858370,22884,4495,3952,4314,4516,5105,4997,2714,1781,328,714,14038,2369,7178,2752,12979,12919,99,9701,9413,3965,1942,783,20,4.291730e+07,2020_1
1395776,2020,1,A,골목상권,1000829,조원로10길,CS100003,일식음식점,1721567998,37934,84,16,15,16,16,18,19,11,5,4,0,36,7,27,26,63,37,0,32,33,15,11,8,1346063577,375504421,213095227,231299151,275121953,277002709,349544537,238188996,137315425,135295000,323470,289273047,95682650,561614562,639379269,966501328,453471955,3656969,361066145,476475637,270114331,198675686,109984514,31250,6684,5280,5814,6279,6757,7120,4197,2487,2248,23,13742,2553,10250,9118,21275,13143,150,11237,11271,5028,3762,2965,29,5.936441e+07,2020_1
1395777,2020,1,A,골목상권,1000829,조원로10길,CS100002,중식음식점,1784915927,84286,75,25,15,15,15,14,16,12,14,4,1,30,13,39,14,64,36,1,26,29,22,16,6,1364816705,420099222,268777897,252963567,266973310,281380969,294720962,218544561,201554661,92347596,10993946,502622902,177224203,695382072,306345208,1044020408,590445993,11209617,470772748,511000932,321457924,229171536,90853642,66115,18171,12374,13145,13236,13443,13917,9348,8823,3265,822,32507,10709,28665,8318,48529,32113,938,26632,23635,14284,10574,4577,31,5.757793e+07,2020_1
1395778,2020,1,A,골목상권,1000829,조원로10길,CS100001,한식음식점,23955751722,754746,77,23,15,15,15,16,17,13,10,3,3,30,10,37,17,68,32,0,19,25,19,21,16,18282318365,5673433357,3174991655,3475388590,3575032860,3770081047,4286824213,3282577478,2390855879,1730689523,526228310,3523601273,1196823896,10013446291,6964962429,14418213930,6688932043,67522067,5181354643,6582324942,3976552790,3295172371,2004219159,597006,157740,112624,118488,118832,121702,125360,87608,70132,44887,37928,243921,59598,238276,130136,470736,238948,2991,189032,213172,122799,108912,72771,288,8.317969e+07,2020_1

In [11]:
df_sales = df.pivot_table(index=['상권_코드', '서비스_업종_코드'], 
               columns='년도_분기', values='점포당_평균_당월_매출')
df_sales.reset_index(inplace=True)
df_sales.shape

(63732, 28)

In [12]:
df_sales.isnull().sum()

년도_분기
상권_코드            0
서비스_업종_코드        0
2014_1        7398
2014_2        7022
2014_3        6856
2014_4        6802
2015_1        6972
2015_2        6627
2015_3        6623
2015_4        6577
2016_1        6796
2016_2        6312
2016_3        5995
2016_4        5820
2017_1        6074
2017_2        5930
2017_3        6312
2017_4        6585
2018_1        6688
2018_2        6567
2018_3        6894
2018_4        6855
2019_1       14413
2019_2       14767
2019_3       14709
2019_4       15347
2020_1       15704
2020_2       15577
dtype: int64

In [13]:
df_sales.dropna(inplace=True)

In [14]:
df_dummies = pd.get_dummies(df_sales['서비스_업종_코드'], drop_first=False)
df_dummies

,CS100001,CS100002,CS100003,CS100004,CS100005,CS100006,CS100007,CS100008,CS100009,CS100010,CS200001,CS200002,CS200003,CS200005,CS200006,CS200007,CS200008,CS200016,CS200017,CS200019,CS200024,CS200025,CS200026,CS200028,CS200029,CS200030,CS200031,CS200032,CS200033,CS200034,CS200036,CS200037,CS300001,CS300002,CS300003,CS300004,CS300006,CS300007,CS300008,CS300009,CS300010,CS300011,CS300014,CS300015,CS300016,CS300017,CS300018,CS300019,CS300020,CS300021,CS300022,CS300024,CS300025,CS300026,CS300027,CS300028,CS300029,CS300031,CS300032,CS300033,CS300035,CS300036,CS300043
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63725,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
63727,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
63728,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
63729,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
63731,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [15]:
df_sales = pd.concat([df_sales, df_dummies], axis=1)
df_sales.shape

(42859, 91)

In [16]:
df_sales.isnull().sum()

상권_코드        0
서비스_업종_코드    0
2014_1       0
2014_2       0
2014_3       0
2014_4       0
2015_1       0
2015_2       0
2015_3       0
2015_4       0
2016_1       0
2016_2       0
2016_3       0
2016_4       0
2017_1       0
2017_2       0
2017_3       0
2017_4       0
2018_1       0
2018_2       0
2018_3       0
2018_4       0
2019_1       0
2019_2       0
2019_3       0
2019_4       0
2020_1       0
2020_2       0
CS100001     0
CS100002     0
CS100003     0
CS100004     0
CS100005     0
CS100006     0
CS100007     0
CS100008     0
CS100009     0
CS100010     0
CS200001     0
CS200002     0
CS200003     0
CS200005     0
CS200006     0
CS200007     0
CS200008     0
CS200016     0
CS200017     0
CS200019     0
CS200024     0
CS200025     0
CS200026     0
CS200028     0
CS200029     0
CS200030     0
CS200031     0
CS200032     0
CS200033     0
CS200034     0
CS200036     0
CS200037     0
CS300001     0
CS300002     0
CS300003     0
CS300004     0
CS300006     0
CS300007     0
CS300008     0
CS300009     0
CS300010     0
CS300011     0
CS300014     0
CS300015     0
CS300016     0
CS300017     0
CS300018     0
CS300019     0
CS300020     0
CS300021     0
CS300022     0
CS300024     0
CS300025     0
CS300026     0
CS300027     0
CS300028     0
CS300029     0
CS300031     0
CS300032     0
CS300033     0
CS300035     0
CS300036     0
CS300043     0
dtype: int64

In [17]:
X = df_sales.drop(['서비스_업종_코드', '2020_2'], axis=1)
y = df_sales['2020_2']

In [18]:
X.head()

,상권_코드,2014_1,2014_2,2014_3,2014_4,2015_1,2015_2,2015_3,2015_4,2016_1,2016_2,2016_3,2016_4,2017_1,2017_2,2017_3,2017_4,2018_1,2018_2,2018_3,2018_4,2019_1,2019_2,2019_3,2019_4,2020_1,CS100001,CS100002,CS100003,CS100004,CS100005,CS100006,CS100007,CS100008,CS100009,CS100010,CS200001,CS200002,CS200003,CS200005,CS200006,CS200007,CS200008,CS200016,CS200017,CS200019,CS200024,CS200025,CS200026,CS200028,CS200029,CS200030,CS200031,CS200032,CS200033,CS200034,CS200036,CS200037,CS300001,CS300002,CS300003,CS300004,CS300006,CS300007,CS300008,CS300009,CS300010,CS300011,CS300014,CS300015,CS300016,CS300017,CS300018,CS300019,CS300020,CS300021,CS300022,CS300024,CS300025,CS300026,CS300027,CS300028,CS300029,CS300031,CS300032,CS300033,CS300035,CS300036,CS300043
0,1000001,6.092752e+07,7.119277e+07,6.941415e+07,8.371927e+07,6.258971e+07,6.645696e+07,6.576536e+07,7.757226e+07,7.015885e+07,7.694477e+07,6.880895e+07,7.875741e+07,7.059091e+07,7.903866e+07,7.526531e+07,8.380275e+07,7.142265e+07,8.301902e+07,7.379520e+07,8.717491e+07,6.061903e+07,6.990543e+07,6.424871e+07,7.248866e+07,4.478399e+07,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1000001,7.830883e+07,7.419328e+07,7.638027e+07,9.373318e+07,6.686465e+07,7.288815e+07,7.048284e+07,8.242502e+07,7.914830e+07,8.162432e+07,7.281198e+07,8.170112e+07,7.565919e+07,6.079148e+07,6.052424e+07,7.421462e+07,6.538066e+07,7.679618e+07,5.656538e+07,8.571366e+07,6.102188e+07,6.731579e+07,6.169022e+07,6.127224e+07,4.493084e+07,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1000001,7.725436e+07,2.934658e+07,4.053009e+07,3.842372e+07,2.944173e+07,3.137040e+07,3.018033e+07,3.600755e+07,2.957095e+07,2.134013e+07,2.047689e+07,1.988962e+07,1.676974e+07,1.191195e+07,1.107833e+07,9.850048e+06,1.566458e+07,1.598102e+07,2.662950e+07,2.784196e+07,2.361333e+07,4.750040e+06,5.968620e+07,5.298060e+07,3.127229e+07,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1000001,8.113118e+07,9.185987e+07,9.243012e+07,1.814898e+08,9.864977e+07,1.076278e+08,9.826663e+07,1.204825e+08,1.249218e+08,1.199577e+08,1.055623e+08,1.214002e+08,1.088533e+08,1.247839e+08,1.048472e+08,1.149784e+08,9.912141e+07,1.228614e+08,1.113682e+08,1.434638e+08,8.218444e+07,7.414365e+07,1.105012e+08,1.324672e+08,1.025918e+08,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1000001,3.476190e+07,3.927323e+07,2.214167e+07,2.165559e+07,6.659322e+07,6.389587e+07,4.910766e+07,4.643170e+07,6.138270e+07,5.458803e+07,4.027121e+07,5.720196e+07,4.004742e+07,3.599730e+07,3.233197e+07,4.706873e+07,4.145602e+07,3.998182e+07,3.790789e+07,4.543281e+07,3.101623e+07,2.955253e+07,2.472802e+07,1.229530e+08,8.340683e+07,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.decomposition import PCA

n_components = 50
whiten = False
random_state = 2020

pca = PCA(n_components=n_components, whiten=whiten, random_state=random_state)

In [20]:
X_pca = pca.fit_transform(X)
X_pca = pd.DataFrame(X_pca)
X_pca.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,8.689189e+07,-1.397034e+07,6.208856e+06,7.118338e+06,-1.500508e+06,2.297665e+06,-1.445274e+07,-3.618876e+06,1.392918e+07,-8.215509e+06,-1.325076e+07,1.086147e+06,-4.098129e+05,6.232932e+05,-5.646521e+06,3.182782e+06,-8.072452e+06,5.192092e+06,1.585078e+06,1.519865e+06,-2.222347e+06,2.816071e+06,-1.604289e+05,-3.241734e+05,1.625261e+06,508.061075,0.714960,-0.435915,0.153932,-0.032342,-0.272316,0.121577,0.001827,-0.107067,-0.074469,-0.103220,-0.125354,-0.054583,0.088165,0.042524,0.053276,-0.082924,-0.061052,0.029116,0.094714,-0.000580,-0.001274,0.024176,0.032188,-0.037907
1,8.230104e+07,-3.065342e+07,-1.871183e+07,2.014788e+07,-5.564198e+06,1.015631e+07,-2.784165e+07,-4.570882e+06,2.102297e+04,-1.308336e+07,-8.821125e+06,-4.175373e+06,-7.993830e+04,2.132454e+06,-3.495846e+06,-3.011095e+06,-1.266677e+07,3.783067e+06,-1.177708e+06,6.994989e+06,-5.178849e+06,-6.409742e+06,9.496092e+05,6.419849e+06,5.416069e+06,512.209056,0.047912,0.010217,0.009400,-0.090823,-0.109853,0.143109,-0.242970,-0.091085,0.819150,-0.008772,0.132424,0.199703,0.179448,0.026129,0.058542,0.083769,0.138935,0.055093,-0.023783,0.045478,-0.001505,0.035689,0.086842,0.021252
2,-1.315517e+08,1.930394e+07,-4.824007e+07,2.619534e+07,1.849213e+07,1.981989e+07,1.111582e+06,-9.016924e+06,8.176637e+06,2.972416e+06,1.534064e+07,-1.767232e+07,-2.242401e+07,-6.284844e+06,8.886809e+06,-2.059799e+07,6.558678e+06,-4.031152e+06,-2.961808e+07,-2.237666e+06,-1.623080e+07,-3.810885e+06,2.101864e+06,-2.777389e+06,1.534863e+06,500.343390,0.005991,-0.004219,0.011820,-0.014835,0.061756,-0.063330,0.023765,0.005199,0.036954,-0.033686,-0.042781,-0.033101,-0.008803,-0.051546,-0.076328,-0.059166,0.034591,-0.045092,-0.007303,-0.199043,-0.071262,0.095789,-0.230661,-0.009079
3,2.847469e+08,-5.564053e+06,-2.591399e+07,-1.126924e+07,-1.534488e+07,1.513016e+07,-4.206247e+07,-1.836494e+06,1.317074e+07,-1.524990e+07,-3.902227e+07,7.050721e+06,-8.411879e+06,-2.684482e+05,3.840278e+07,1.172081e+07,-3.127011e+07,7.871987e+06,-1.740641e+07,-7.682924e+06,-2.124748e+07,2.379615e+07,-1.209767e+07,1.378571e+07,-6.377477e+06,507.272143,-0.007405,-0.014124,-0.010956,-0.017172,-0.061838,-0.001831,-0.016577,0.019465,0.009435,0.023411,0.013861,-0.010865,-0.017034,0.000887,0.017042,-0.024152,-0.112941,-0.048885,0.068702,-0.024619,0.013063,0.101205,-0.031334,0.076641
4,-3.635717e+07,6.296436e+07,-5.553979e+07,-3.412998e+07,-3.731597e+07,-1.278208e+07,4.916405e+06,-2.465299e+06,7.517450e+06,-8.261607e+06,2.090331e+07,-1.384957e+07,6.959925e+06,1.997813e+07,-1.701716e+07,3.971984e+06,-8.725279e+06,-5.233508e+06,-7.304047e+05,-3.210483e+06,8.863350e+05,9.160273e+06,8.733305e+06,-3.992413e+06,1.127340e+06,515.190320,-0.001597,-0.060698,0.051387,-0.042593,-0.105806,0.015607,0.082547,0.219648,-0.285537,-0.370992,0.236717,0.631504,-0.080708,-0.156625,0.157947,0.145321,0.190771,-0.025648,-0.057406,0.003733,0.079995,-0.152863,0.021960,0.024461

In [21]:
print('Variance Explained by all PCA_rev:', 
                      sum(pca.explained_variance_ratio_))

Variance Explained by all PCA_rev: 0.9999999999999996

In [22]:
# X개의 주성분으로 추출한 원본 데이터의 분산 비율

importanceOfPrincipalComponents_rev = \
    pd.DataFrame(data=pca.explained_variance_ratio_)
importanceOfPrincipalComponents_rev = importanceOfPrincipalComponents_rev.T

print('Variance Captured by First 10 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:9].sum(axis=1).values)
print('Variance Captured by First 20 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:19].sum(axis=1).values)
print('Variance Captured by First 23 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:22].sum(axis=1).values)
print('Variance Captured by First 24 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:23].sum(axis=1).values)
print('Variance Captured by First 25 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:24].sum(axis=1).values)
print('Variance Captured by First 50 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:49].sum(axis=1).values)
print('Variance Captured by First 100 Principal Components: ',
      importanceOfPrincipalComponents_rev.loc[:,0:99].sum(axis=1).values)

Variance Captured by First 10 Principal Components:  [0.96422022]
Variance Captured by First 20 Principal Components:  [0.99418892]
Variance Captured by First 23 Principal Components:  [0.99809166]
Variance Captured by First 24 Principal Components:  [0.99919103]
Variance Captured by First 25 Principal Components:  [1.]
Variance Captured by First 50 Principal Components:  [1.]
Variance Captured by First 100 Principal Components:  [1.]

## Parameter 재설정

In [23]:
n_components = 25
whiten = False
random_state = 2020

pca = PCA(n_components=n_components, whiten=whiten, random_state=random_state)

X_pca = pca.fit_transform(X)
X_pca = pd.DataFrame(X_pca)

## Train/Test Split

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_pca, y,
                                                    test_size=0.3, random_state=10)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(len(X_train) + len(X_test))

(30001, 25)
(12858, 25)
(30001,)
(12858,)
42859

## 모델링 + 하이퍼파라미터

In [45]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet, HuberRegressor

# from sklearn.linear_model import PassiveAggressiveRegressor, RANSACRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.kernel_ridge import KernelRidge

# from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

# from sklear.svm import NuSVR
import xgboost
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [46]:
## Pre-allocate models and corresponding parameter candidates
models = []
params = []

In [47]:
model = ('Ridge', Ridge())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]
}

models.append(model)
params.append(param)

In [48]:
model = ('Lasso', Lasso())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]
}

models.append(model)
params.append(param)

In [49]:
model = ('ElasticNet', ElasticNet())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0],
    'l1_ratio': [0.3, 0.5, 0.7]
}

models.append(model)
params.append(param)

In [50]:
model = ('HuberReg', HuberRegressor())
param = {
    'alpha': [0.0001, 0.001, 0.01]
}

models.append(model)
params.append(param)

In [51]:
model = ('CART', DecisionTreeRegressor())
param = {
    'max_depth': [2, 3, 4, 5],
    'min_samples_split': [0.02, 0.05]
}

models.append(model)
params.append(param)

In [52]:
model = ('StandardizedKNN', Pipeline([('Standardization', StandardScaler()), ('KNN', KNeighborsRegressor())]))
param = {
    'KNN__n_neighbors': [5, 10, 15, 20, 25, 30],
    'KNN__weights': ['uniform', 'distance']
}

models.append(model)
params.append(param)

In [53]:
model = ('XGB', XGBRegressor())
param = {'min_child_weight':[0.5, 1.0], 
         'gamma': [0.04],
         'subsample': [0.5],
         'colsample_bytree': [0.5],
         'max_depth': [3, 4]
        
}
models.append(model)
params.append(param)

In [54]:
from pprint import pprint
pprint(models)
print("=" * 60)
pprint(params)

[('Ridge', Ridge()),
 ('Lasso', Lasso()),
 ('ElasticNet', ElasticNet()),
 ('HuberReg', HuberRegressor()),
 ('CART', DecisionTreeRegressor()),
 ('StandardizedKNN',
  Pipeline(steps=[('Standardization', StandardScaler()),
                ('KNN', KNeighborsRegressor())])),
 ('XGB',
  XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=None, gamma=None,
             gpu_id=None, importance_type='gain', interaction_constraints=None,
             learning_rate=None, max_delta_step=None, max_depth=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             random_state=None, reg_alpha=None, reg_lambda=None,
             scale_pos_weight=None, subsample=None, tree_method=None,
             validate_parameters=None, verbosity=None))]
============================================================
[{'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]},
 {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]},
 {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0], 'l1_ratio': [0.3, 0.5, 0.7]},
 {'alpha': [0.0001, 0.001, 0.01]},
 {'max_depth': [2, 3, 4, 5], 'min_samples_split': [0.02, 0.05]},
 {'KNN__n_neighbors': [5, 10, 15, 20, 25, 30],
  'KNN__weights': ['uniform', 'distance']},
 {'colsample_bytree': [0.5],
  'gamma': [0.04],
  'max_depth': [3, 4],
  'min_child_weight': [0.5, 1.0],
  'subsample': [0.5]}]

## GridSearch with K-fold CV

In [55]:
from sklearn.model_selection import KFold, GridSearchCV
from sklearn import metrics
from datetime import datetime

In [56]:
def gridsearch_cv_for_regression(model, param, kfold, train_input, train_target, scoring='neg_mean_squared_error', n_jobs=-1, tracking=True):

    name = model[0]
    estimator = model[1]
    if tracking:
        start_time = datetime.now()
        print("[%s] Start parameter search for model '%s'" % (start_time, name))
        gridsearch = GridSearchCV(estimator=estimator, param_grid=param, cv=kfold, scoring=scoring, n_jobs=n_jobs)
        gridsearch.fit(train_input, train_target)
        end_time = datetime.now()
        duration_time = (end_time - start_time).seconds
        print("[%s] Finish parameter search for model '%s' (time: %d seconds)" % (end_time, name, duration_time))
        print()
    else:
        gridsearch = GridSearchCV(estimator=estimator, param_grid=param, cv=kfold, scoring=scoring, n_jobs=n_jobs)
        gridsearch.fit(train_input, train_target)
    
    return gridsearch

In [57]:
kfold = KFold(n_splits=10, 
              shuffle=True, 
              random_state=1234)

In [58]:
# Grid search
kfold = KFold(n_splits=10, shuffle=True, random_state=1234)

results = []

for i in range(len(models)):
#for i in range(6):
    model = models[i]
    param = params[i]
    result = gridsearch_cv_for_regression(model=model, param=param, kfold=kfold, train_input=X_train, train_target=y_train)
    print(result.best_score_)
    print(result.best_params_)
    results.append(result)

[2021-07-17 23:18:58.879723] Start parameter search for model 'Ridge'
[2021-07-17 23:19:01.079931] Finish parameter search for model 'Ridge' (time: 2 seconds)

-1409421659748241.0
{'alpha': 0.1}
[2021-07-17 23:19:01.080196] Start parameter search for model 'Lasso'
[2021-07-17 23:19:36.677459] Finish parameter search for model 'Lasso' (time: 35 seconds)

-1409421659748234.0
{'alpha': 10.0}
[2021-07-17 23:19:36.677630] Start parameter search for model 'ElasticNet'
[2021-07-17 23:21:28.924986] Finish parameter search for model 'ElasticNet' (time: 112 seconds)

-1409421659748234.0
{'alpha': 10.0, 'l1_ratio': 0.3}
[2021-07-17 23:21:28.925189] Start parameter search for model 'HuberReg'
[2021-07-17 23:21:34.116026] Finish parameter search for model 'HuberReg' (time: 5 seconds)

-1.3608414418697588e+16
{'alpha': 0.0001}
[2021-07-17 23:21:34.116207] Start parameter search for model 'CART'
[2021-07-17 23:21:36.403940] Finish parameter search for model 'CART' (time: 2 seconds)

-5089624920669406.0
{'max_depth': 5, 'min_samples_split': 0.02}
[2021-07-17 23:21:36.404072] Start parameter search for model 'StandardizedKNN'
[2021-07-17 23:22:23.423336] Finish parameter search for model 'StandardizedKNN' (time: 47 seconds)

-3647085047714148.0
{'KNN__n_neighbors': 5, 'KNN__weights': 'distance'}
[2021-07-17 23:22:23.423537] Start parameter search for model 'XGB'
[2021-07-17 23:22:43.713590] Finish parameter search for model 'XGB' (time: 20 seconds)

-3293157807354253.5
{'colsample_bytree': 0.5, 'gamma': 0.04, 'max_depth': 3, 'min_child_weight': 0.5, 'subsample': 0.5}

## Metrics

In [59]:
def MAPE(y_test, y_pred): 
    y_test, y_pred = np.array(y_test), np.array(y_pred)
    mape = 100 - (np.mean(np.abs((y_test - y_pred) / y_test)) * 100)
    return mape


def RMSPE(y_test, y_pred):
    y_test, y_pred = np.array(y_test), np.array(y_pred)
    rmspe = 100 - (np.sqrt(np.mean(((y_test - y_pred) / y_test)**2))*100)
    return rmspe

In [60]:
for i in range(len(results)):
    y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(y_test, y_test_hat))
    mae = metrics.mean_absolute_error(y_test, y_test_hat)
    r2 = metrics.r2_score(y_test, y_test_hat)
    mape = MAPE(y_test, y_test_hat)
    rmspe = RMSPE(y_test, y_test_hat)
    
    print("## %s | RMSE: %.4f, MAE: %.4f, R-square: %.4f, Relative Absolute Error: %.4f%%" % (models[i][0], rmse, mae, r2, mape))

## Ridge | RMSE: 33008366.2102, MAE: 11744522.8504, R-square: 0.9116, Relative Absolute Error: -426.2379%
## Lasso | RMSE: 33008366.2102, MAE: 11744522.8504, R-square: 0.9116, Relative Absolute Error: -426.2379%
## ElasticNet | RMSE: 33008366.2102, MAE: 11744522.8504, R-square: 0.9116, Relative Absolute Error: -426.2379%
## HuberReg | RMSE: 122046076.6224, MAE: 54476427.6382, R-square: -0.2080, Relative Absolute Error: -879.0751%
## CART | RMSE: 77310250.6493, MAE: 23710762.7355, R-square: 0.5153, Relative Absolute Error: -2997.0544%
## StandardizedKNN | RMSE: 57853263.9210, MAE: 17567721.6475, R-square: 0.7286, Relative Absolute Error: -250.8067%
## XGB | RMSE: 45313590.8032, MAE: 14746314.0945, R-square: 0.8335, Relative Absolute Error: -2131.6942%

In [61]:
for i in range(len(params)):
    print(models[i][0], params[i])

Ridge {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]}
Lasso {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]}
ElasticNet {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0], 'l1_ratio': [0.3, 0.5, 0.7]}
HuberReg {'alpha': [0.0001, 0.001, 0.01]}
CART {'max_depth': [2, 3, 4, 5], 'min_samples_split': [0.02, 0.05]}
StandardizedKNN {'KNN__n_neighbors': [5, 10, 15, 20, 25, 30], 'KNN__weights': ['uniform', 'distance']}
XGB {'min_child_weight': [0.5, 1.0], 'gamma': [0.04], 'subsample': [0.5], 'colsample_bytree': [0.5], 'max_depth': [3, 4]}

In [62]:
outcome = pd.DataFrame(columns = ['Model', 'Parameters', 'RMSE', 'RMSPE', 'MAE', 'MAPE', 'R-squared' ])
for i in range(len(models)):
    y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(y_test, y_test_hat))
    mae = metrics.mean_absolute_error(y_test, y_test_hat)
    r2 = metrics.r2_score(y_test, y_test_hat)
    outcome = outcome.append(pd.DataFrame([[models[i][0], params[i], rmse , rmspe, mae, mape, r2]],
                                 columns = ['Model', 'Parameters', 'RMSE', 'RMSPE', 'MAE', 'MAPE', 'R-squared']),
                    ignore_index=True)
    
outcome

,Model,Parameters,RMSE,RMSPE,MAE,MAPE,R-squared
0,Ridge,"{'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]}",3.300837e+07,-222160.860776,1.174452e+07,-2131.694155,0.911637
1,Lasso,"{'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]}",3.300837e+07,-222160.860776,1.174452e+07,-2131.694155,0.911637
2,ElasticNet,"{'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]...",3.300837e+07,-222160.860776,1.174452e+07,-2131.694155,0.911637
3,HuberReg,"{'alpha': [0.0001, 0.001, 0.01]}",1.220461e+08,-222160.860776,5.447643e+07,-2131.694155,-0.208003
4,CART,"{'max_depth': [2, 3, 4, 5], 'min_samples_split...",7.731025e+07,-222160.860776,2.371076e+07,-2131.694155,0.515276
5,StandardizedKNN,"{'KNN__n_neighbors': [5, 10, 15, 20, 25, 30], ...",5.785326e+07,-222160.860776,1.756772e+07,-2131.694155,0.728559
6,XGB,"{'min_child_weight': [0.5, 1.0], 'gamma': [0.0...",4.531359e+07,-222160.860776,1.474631e+07,-2131.694155,0.833476